USE socialmediadb;


-- Insert data into the Posts table for some users
INSERT INTO Posts (UserID, PostContent, PostDate)
VALUES
(1, 'My first post on this platform!', NOW()),
(2, 'Hello, world!', NOW()),
(3, 'Enjoying the sunshine today!', NOW()),
(4, 'Anyone up for a coding challenge?', NOW()),
(5, 'Sharing my latest blog article!', NOW()),
(6, 'Exploring new places is always fun.', NOW()),
(7, 'Who else is excited for the weekend?', NOW()),
(8, 'Learning SQL is so much fun!', NOW()),
(9, 'Just completed a 10k run!', NOW()),
(10, 'Back to school season!', NOW()), -- Added missing comma
(11, 'Just started a new job!', NOW()),
(12, 'Loving the new features in this app!', NOW()),
(13, 'Hiking in the mountains this weekend!', NOW()),
(14, 'Who’s up for a movie night?', NOW()),
(15, 'Reading an amazing book on tech trends.', NOW()),
(16, 'What’s everyone’s favorite programming language?', NOW()),
(17, 'Trying out a new recipe today!', NOW()),
(18, 'Completed a full marathon!', NOW()),
(19, 'Looking for project collaboration ideas.', NOW()),
(20, 'Best coffee spots in town?', NOW()),
(1, 'Planning my next travel destination.', NOW()),
(2, 'Coding all day is so satisfying.', NOW()),
(3, 'Latest tech news is mind-blowing!', NOW()),
(4, 'Need some coding tips.', NOW()),
(5, 'Excited to start a new project!', NOW());

-- Insert data into the Comments table for some posts
INSERT INTO Comments (PostID, UserID, CommentContent, CommentDate)
VALUES
(1, 2, 'Congrats on your first post!', NOW()),
(2, 3, 'Welcome!', NOW()),
(3, 4, 'That sounds great!', NOW()),
(4, 5, 'I am! Let’s do this!', NOW()),
(5, 6, 'Looking forward to reading it!', NOW()),
(6, 7, 'Traveling is the best!', NOW()),
(7, 8, 'Absolutely!', NOW()),
(8, 9, 'It really is!', NOW()),
(9, 10, 'Great job!', NOW()),
(10, 1, 'Hope everyone has a great school year!', NOW()),
(11, 1, 'Congratulations!', NOW()),
(12, 2, 'I noticed that too!', NOW()),
(13, 3, 'Hiking is so refreshing.', NOW()),
(14, 4, 'Count me in!', NOW()),
(15, 5, 'What book are you reading?', NOW()),
(16, 6, 'Python is my favorite!', NOW()),
(17, 7, 'Good luck!', NOW()),
(18, 8, 'Amazing achievement!', NOW()),
(19, 9, 'Would love to brainstorm with you.', NOW()),
(20, 10, 'Try the new place downtown.', NOW()),
(1, 11, 'Where are you planning to go?', NOW()),
(2, 12, 'True, it’s great!', NOW()),
(3, 13, 'Yes, very interesting!', NOW()),
(4, 14, 'I have a few tips to share.', NOW()),
(5, 15, 'Can’t wait to see your project.', NOW()),
(6, 16, 'Enjoy the process!', NOW()),
(7, 17, 'Yes, weekends are the best!', NOW()),
(8, 18, 'Totally agree.', NOW()),
(9, 19, '10k is impressive.', NOW()),
(10, 20, 'Good luck with your school year!', NOW());

-- Insert data into the Reactions table for some posts
INSERT INTO Reactions (PostID, UserID, ReactionType, ReactionDate)
VALUES
(1, 3, 'Like', NOW()),
(1, 4, 'Love', NOW()),
(2, 5, 'Haha', NOW()),
(2, 6, 'Wow', NOW()),
(3, 7, 'Like', NOW()),
(4, 8, 'Love', NOW()),
(5, 9, 'Sad', NOW()),
(6, 10, 'Angry', NOW()),
(7, 1, 'Like', NOW()),
(8, 2, 'Love', NOW()),
(9, 3, 'Haha', NOW()),
(10, 4, 'Wow', NOW()),
(11, 3, 'Like', NOW()),
(12, 4, 'Love', NOW()),
(13, 5, 'Wow', NOW()),
(14, 6, 'Like', NOW()),
(15, 7, 'Haha', NOW()),
(16, 8, 'Like', NOW()),
(17, 9, 'Love', NOW()),
(18, 10, 'Wow', NOW()),
(19, 1, 'Like', NOW()),
(20, 2, 'Love', NOW()),
(1, 3, 'Haha', NOW()),
(2, 4, 'Wow', NOW()),
(3, 5, 'Sad', NOW()),
(4, 6, 'Angry', NOW()),
(5, 7, 'Like', NOW()),
(6, 8, 'Love', NOW()),
(7, 9, 'Haha', NOW()),
(8, 10, 'Wow', NOW()),
(9, 11, 'Like', NOW()),
(10, 12, 'Love', NOW()),
(11, 13, 'Sad', NOW()),
(12, 14, 'Haha', NOW()),
(13, 15, 'Angry', NOW()),
(14, 16, 'Wow', NOW()),
(15, 17, 'Like', NOW()),
(16, 18, 'Love', NOW()),
(17, 19, 'Sad', NOW()),
(18, 20, 'Haha', NOW());
